services:
  - type: web
    name: healthifyai-backend
    env: python
    plan: free
    rootDir: ./backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COLAB_URL
        sync: false
